services:
  db:
    image: "mariadb:lts"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./env/db.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./dockerfile/backend.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./env/backend.env
#    depends_on:
#      - db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./dockerfile/frontend.dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_HOST: localhost:8080

volumes:
  data: