services:
  db:
    image: "mariadb:lts"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./env/db.env

  backend:
    build:
      context: .
      dockerfile: ./dockerfile/backend.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./env/backend.env

  frontend:
    build:
      context: .
      dockerfile: ./dockerfile/frontend.dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./env/frontend.env

volumes:
  data: